import { VirtualDomElements } from '@lvce-editor/constants'
import * as ElementTags from '../ElementTags/ElementTags.ts'

const tagMap: Record<string, number> = {
  [ElementTags.A]: VirtualDomElements.A,
  [ElementTags.Abbr]: VirtualDomElements.Abbr,
  [ElementTags.Article]: VirtualDomElements.Article,
  [ElementTags.Aside]: VirtualDomElements.Aside,
  [ElementTags.Br]: VirtualDomElements.Br,
  [ElementTags.Button]: VirtualDomElements.Button,
  [ElementTags.Canvas]: VirtualDomElements.Canvas,
  [ElementTags.Cite]: VirtualDomElements.Cite,
  [ElementTags.Code]: VirtualDomElements.Code,
  [ElementTags.Data]: VirtualDomElements.Data,
  [ElementTags.Dd]: VirtualDomElements.Dd,
  [ElementTags.Del]: VirtualDomElements.Del,
  [ElementTags.Div]: VirtualDomElements.Div,
  [ElementTags.Dl]: VirtualDomElements.Dl,
  [ElementTags.Dt]: VirtualDomElements.Dt,
  [ElementTags.Figcaption]: VirtualDomElements.Figcaption,
  [ElementTags.Figure]: VirtualDomElements.Figure,
  [ElementTags.Footer]: VirtualDomElements.Footer,
  [ElementTags.Form]: VirtualDomElements.Div,
  [ElementTags.H1]: VirtualDomElements.H1,
  [ElementTags.H2]: VirtualDomElements.H2,
  [ElementTags.H3]: VirtualDomElements.H3,
  [ElementTags.H4]: VirtualDomElements.H4,
  [ElementTags.H5]: VirtualDomElements.H5,
  [ElementTags.H6]: VirtualDomElements.H6,
  [ElementTags.Header]: VirtualDomElements.Header,
  [ElementTags.Hr]: VirtualDomElements.Hr,
  [ElementTags.Iframe]: VirtualDomElements.Iframe,
  [ElementTags.Img]: VirtualDomElements.Img,
  [ElementTags.Input]: VirtualDomElements.Input,
  [ElementTags.Label]: VirtualDomElements.Label,
  [ElementTags.Li]: VirtualDomElements.Li,
  [ElementTags.Nav]: VirtualDomElements.Nav,
  [ElementTags.Ol]: VirtualDomElements.Ol,
  [ElementTags.Option]: VirtualDomElements.Option,
  [ElementTags.P]: VirtualDomElements.P,
  [ElementTags.Pre]: VirtualDomElements.Pre,
  [ElementTags.Search]: VirtualDomElements.Search,
  [ElementTags.Section]: VirtualDomElements.Section,
  [ElementTags.Strong]: VirtualDomElements.Strong,
  [ElementTags.Select]: VirtualDomElements.Select,
  [ElementTags.Span]: VirtualDomElements.Span,
  [ElementTags.Table]: VirtualDomElements.Table,
  [ElementTags.TBody]: VirtualDomElements.TBody,
  [ElementTags.Td]: VirtualDomElements.Td,
  [ElementTags.TextArea]: VirtualDomElements.TextArea,
  [ElementTags.Tfoot]: VirtualDomElements.Tfoot,
  [ElementTags.Th]: VirtualDomElements.Th,
  [ElementTags.THead]: VirtualDomElements.THead,
  [ElementTags.Time]: VirtualDomElements.Time,
  [ElementTags.Tr]: VirtualDomElements.Tr,
  [ElementTags.Ul]: VirtualDomElements.Ul,
  html: VirtualDomElements.Html,
  style: VirtualDomElements.Style,
}

export const getVirtualDomTag = (text: string): number => {
  return tagMap[text] ?? VirtualDomElements.Div
}
